### PR TITLE
Correction of Serbian translation

### PR DESCRIPTION
**Pull request by nemanya-d**
Current translator uses poor quality translations for both LocalSend website and app, not following any grammar and translation rules, etc.

### CODE REVIEW

**Comment by nebojsatomic** [comment]
@nemanya-d  most of your contribution that you did was replacing certain words with synonyms. Just to be added as a contributor, I might say.

**Comment by nemanya-d** [comment]
> @nemanya-d most of your contribution was replacing certain words with synonyms. Just to be added as a contributor, I might say.

No. I replaced untranslated and poorly translated strings. I didn't change those that are good.

Untranslated – you simply didn't use any translation for certain words (you would simply leave it in English), even though there is an adequate word for it in Serbian.

Poorly translated – you didn't respect many grammatical rules, for example you often leave a capital letter in the middle of the sentence (isn't correct in the Serbian language); you literally translated some sentences from English to Serbian (sounds unnatural and isn't correct); you lack consistency in your translations; you should refer to users "na Vi" in translations that aren't clickable and in the ones that are clickable (for example, buttons) you should refer to users "na Ti" (again, sticking to Google's and Microsoft's translations and translation rules in general).

Examples: "{os} Preuzimanja" sounds unnatural, contains capital letter after the first word (which is incorrect) and it can be understood as something different – it should be translated as "Preuzimanja za {os}" ([for example, you can see it in [Microsoft's translation](https://support.microsoft.com/sr-latn-rs/windows/preuzimanja-za-windows-32490f9b-01ee-c13e-b2af-b5057c2d34e8)); "Enkripcija" is incorrect and just an anglicism and it should be "Šifrovanje" (as both [Google](https://support.google.com/messages/answer/10262381?hl=sr&sjid=6575271283953306896-EU) and [Microsoft](https://support.microsoft.com/sr-latn-rs/windows/%C5%A1ifrovanje-ure%C4%91aja-u-operativnom-sistemu-windows-cf7e2b6f-3e70-4882-9532-18633605b7df) translated), etc.

I have translated a lot of projects, for many years now, so I really have experience and over time I have corrected the mistakes I made myself, sometimes also by listening to someone more experienced. One of the most important tips – it would be the best to follow Google's or Microsoft's (their websites, apps) translations because they are relevant and they surely have very professional translators. The translation must be consistent, you cannot translate a word in one way somewhere, and another way somewhere else, and somewhere else not at all. You have to translate everything so that it is as understandable as possible for the users.

I hope you'll understand.

**Comment by nebojsatomic** [comment]
@nemanya-d  Are you working for Microsoft or Google when you translate this app?
If I left something in English, it was because I thought that it would be more understandable like that.
If you wanted to stick to the standards, you shouldn't have written your name in Cyrillic script here on Github in the first place, a lot more people would understand and know how to pronounce it, at least better than now - Nemanja Dimitrijević would be a lot better than Немања Димитријевић.

This is also not Facebook to have this kind of communication. You could have simply written a better reason for proposing this change, one that would not be sounding insulting, and I would have said nothing about it.

**Comment by nebojsatomic** [comment]
This is a problem with most serbian translations everywhere,  when people try to translate to Serbian every single english word, and then we end up with very funny sounding words. For example, I left 'Pull Request' be 'Pull Request', and you translated it to 'Zahtev za povlačenje' which sounds very unnatural in the developer world, and translated back to English would likely be translated more like a 'Request for pulling' or something similar, also not appropriate. No developer, anywhere in the world would say anything else other than 'Pull Request'.

It is up to the owner of this project to decide if this changing of words into their synonyms, and translating every single word into their serbian counterpart is something that he wants to do.
If it was my project, I wouldn't.

**Comment by nemanya-d** [comment]
Again, you left many strings untranslated, badly translated, not following many grammar rules, being inconsistent. Don't just stick to certain translations that you don't like, even though they are more correct.

**I would be glad if you can finally understand that exactly for all those reasons you should be guided by translations from professional translators, such as those who work at Google, Microsoft or any other big company.** These are people with years of translating experience, you won't find untranslated strings there, because they thought it was more understandable. They will surely find the best translation. In extremely rare cases, they will leave the English word, when there is no adequate Serbian translation for it (example, "peer-to-peer").

By the way, you said this is not Facebook, not me.

**Comment by nemanya-d** [comment]
> Yes, I see that you still act like you are on FB.
> 
> I will not stop you from doing whatever you want to do, no matter how arrogant you seem to be, take pleasure in contributing. To me you are just a person who doesn't understand that it is better to leave english words in their original form when everybody knows what they mean.

You are the one acting like this is Facebook by constantly replying. Should I just be silent on your false accusations towards me?

I'm not arrogant, I'm only following translate the most correct translations, which you certainly don't do. I'm advised by professional translators.

You should just accept the fact that I only gave you advices and I corrected the mistakes. This is nothing as serious as you see it. Not liking the correct translations doesn't mean that they are incorrect.

Thanks.

**Comment by nebojsatomic** [comment]
'Zahtev za povlačenje' ( according to @nemanya-d  - Pull Request ) is something that every serbian  developer will laugh about the next time he/she receives one, and doesn't know how many times to pull you, or some part of you, or simply - retire. There are many meanings behind this string that can come to mind, but none of them will be Pull Request.

@Tienisto I am sorry to make this go on, I will not make another comment about this, and @nemanya-d  will make some long text again, I am sure.

**Comment by nemanya-d** [comment]
**Addition:** As I'm a reasonable person, who listens to others and accepts mistakes made (unlike individuals), I changed the translation that annoyed you. Now the translation is simply an English word adjusted to the Serbian language rules "Pull requestovi" for Serbian (Latin) and "Pull request-ови" for Serbian (Cyrillic).

I hope you're satisfied now @nebojsatomic 😀

**Pull request merged**
