### PR TITLE
updated pc screenshot

### PR DESCRIPTION
**Pull request by mijorus**
Updated screenshot with a modern looking laptop

### CODE REVIEW

**Comment by Tienisto** [comment]
I think this image is too much 3D and doesn't fit with the mobile screenshot.

Screenshot 2023-12-03 at 14 43 56

**Comment by sergd88** [comment]
I can suggest an option with narrowed down frames.

old vs new

[screenshot-pc-new.zip](https://github.com/localsend/website/files/13660615/screenshot-pc-new.zip)

**Comment by sergd88** [comment]
I can suggest an option with narrowed down frames.

old vs new

[screenshot-pc-new.zip](https://github.com/localsend/website/files/13660994/screenshot-pc-new.zip)

**Comment by sergd88** [comment]
@Tienisto I can suggest an option with narrowed down frames.

old vs new

[screenshot-pc-new.zip](https://github.com/localsend/website/files/13661010/screenshot-pc-new.zip)

**Pull request closed without merging**
